# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('counsler', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
